### ISSUE TITLE
Badass game, though I couldn't shoot the last enemy

### ISSUE THREAD

**Issue by jason-o-matic** [indymichelle/galaga#1]
The last little dude was at the very top of the screen, maybe 1/5th from the right.  It looked like my bullets just wouldn't quite reach him or something.

**Comment by jqr** [comment]
Yeah we've seen this behavior, the hit detection is currently only checking the top left corner of the shot and it actually needs to take into account the width of the shot.

**Comment by jason-o-matic** [comment]
It took me a few restarts but I managed to see it again.  I've attached a screenshot just in case it's helpful.

![Screen shot 2013-04-02 at 8 44 18 PM](https://f.cloud.github.com/assets/13733/331682/b5131708-9bf7-11e2-9f1a-b0694a41e0cc.png)

**Comment by janxious** [comment]
Does the sprite collision take into account the empty parts of the sprite? I don't actually know how real Galaga does it. But I assume this is going to be Ultra Galaga, with cheevos and MOTHER FUCKING WIZARDS and dragons and shit.

**Comment by indymichelle** [comment]
@Jason - have you tried shooting the shit out of the enemy?

I have an idea as to what might be causing the issue.  I'll get to fixin it tonight.

**Comment by indymichelle** [comment]
And by "tonight" I actually meant tomorrow.

Also what browser are you using?
